In [1]:
# import libraries
import pandas as pd
import os
from sqlalchemy import create_engine

In [2]:

# create database engine
engine = create_engine(
    "mysql+mysqlconnector://root:pricass00@localhost:3306/olist_db",
    echo=False
)

In [3]:

# path to cleaned csv files
CLEANED_DATA_PATH = r"C:\Users\offic\Downloads\onedrive pl\OneDrive\Desktop\PRIXDATA\PRO\ecommerce_olist_data\cleaned"

In [4]:

# map csv files to table names
file_table_map = {
    "cleaned_orders.csv": "orders_clean",
    "cleaned_order_items.csv": "order_items_clean",
    "cleaned_products.csv": "products_clean",
    "cleaned_order_payments.csv": "order_payments_clean"
}

In [5]:

# loop through each file and table
for file, table in file_table_map.items():
    # full file path
    file_path = os.path.join(CLEANED_DATA_PATH, file)

    print(f"\nLoading {file} → {table}")

    # read csv file
    df = pd.read_csv(file_path, low_memory=False)

    # clean column names
    df.columns = (
        df.columns
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.replace("/", "_")
    )

    # convert datetime columns to string (if any)
    for col in df.select_dtypes(include=["datetime64[ns]"]).columns:
        df[col] = df[col].astype(str)

    # write dataframe to mysql table
    df.to_sql(
        name=table,
        con=engine,
        if_exists="replace",
        index=False,
        method="multi"
    )

    print(f"{table} loaded successfully")

Loading cleaned_orders.csv → orders_clean
orders_clean loaded successfully

Loading cleaned_order_items.csv → order_items_clean
order_items_clean loaded successfully

Loading cleaned_products.csv → products_clean
products_clean loaded successfully

Loading cleaned_order_payments.csv → order_payments_clean
order_payments_clean loaded successfully

In [6]:
tables = [
    "orders_clean",
    "order_items_clean",
    "products_clean",
    "order_payments_clean"
]

In [7]:

for table in tables:
    query = f"SELECT COUNT(*) AS row_count FROM {table}"
    count_df = pd.read_sql(query, engine)
    print(f"{table}: {count_df.iloc[0,0]} rows")

orders_clean: 99441 rows
order_items_clean: 112650 rows
products_clean: 32951 rows
order_payments_clean: 103886 rows

In [8]:
for table in tables:
    print(f"\nPreview of {table}")
    display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5", engine))

Preview of orders_clean

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,data_quality_missing_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0

Preview of order_items_clean

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,data_quality_missing_count
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,0

Preview of products_clean

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,data_quality_missing_count
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,0

Preview of order_payments_clean

,order_id,payment_sequential,payment_type,payment_installments,payment_value,data_quality_missing_count
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,0
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,0
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,0
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,0
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,0

In [9]:
for table in tables:
   df = pd.read_sql(f"SELECT * FROM {table}", engine)
   null_count = df.isnull().sum().sum()
   print(f"{table} → total NULL values: {null_count}")

orders_clean → total NULL values: 4748
order_items_clean → total NULL values: 0
products_clean → total NULL values: 0
order_payments_clean → total NULL values: 0

In [10]:
df = pd.read_sql("SELECT * FROM orders_clean", engine)

df.isnull().sum().sort_values(ascending=False)

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_id                            0
customer_id                         0
order_status                        0
order_approved_at                   0
order_purchase_timestamp            0
order_estimated_delivery_date       0
data_quality_missing_count          0
dtype: int64

In [11]:
df = pd.read_sql(
    "SELECT * FROM olist_orders_analytics",
    engine
)
df.to_csv(
    "olist_orders_analytics.csv",
    index=False
)